// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {indentation} from "./tokens"
const spec_Identifier = {__proto__:null,node:14, true:64, false:66, say:116, choice:120, if:126, goto:130, end:132}
export const parser = LRParser.deserialize({
  version: 14,
  states: "-UQYQPOOOOQO'#Dq'#DqQYQPOOO_QPO'#CaOOQO-E7o-E7oOdQPO,58{OiQXO1G.gOnQPO7+$RO|QPO'#CgO!RQPO'#CfOOQW'#Ce'#CeOOQW'#Dr'#DrO!dQXO<<GmO!uQPO'#DgO!zQPO'#DiO#PQPO'#DnOOQO,59R,59ROOQO'#Ci'#CiO#UQQO,59QOOQW-E7p-E7pO#sQPOAN=XO#xQPO,5:RO#}QPO,5:TO$SQPO'#DkO$XQPO,5:YOOQO'#Cv'#CvO$^QPO'#DPO#UQQO'#DSOOQO'#Cy'#CyO#UQQO'#CuOOQO'#Cu'#CuO%QQSO'#CtO&PQSO'#CsO&gQSO'#CrO'[QPO'#CqO'mQPO'#CpOOQO'#Co'#CoO'{QPO1G.lOOQOG22sG22sOOQW1G/m1G/mO#PQPO1G/oOOQO,5:V,5:VOOQW1G/t1G/tO(QQQO,59kO(XQPO,59nOOQO,59a,59aOOQO'#DT'#DTOOQO'#DV'#DVO#UQQO'#DtO({QSO,59`OOQO'#DX'#DXOOQO'#DZ'#DZO#UQQO'#DuO)zQSO,59_OOQO'#D['#D[O#UQQO,59^OOQO'#Dc'#DcO#UQQO'#DvO*bQPO,59]OOQO'#De'#DeO#UQQO'#DwO*sQPO,59[OOQW7+$W7+$WO+RQPO7+%ZOOQO1G/V1G/VO+ZQPO1G/VOOQO1G/Y1G/YOOQO,5:`,5:`OOQO-E7r-E7rOOQO,5:a,5:aOOQO-E7s-E7sO$cQQO'#CtO%hQQO'#CsOOQO1G.x1G.xOOQO,5:b,5:bOOQO-E7t-E7tOOQO,5:c,5:cOOQO-E7u-E7uOOQW<<Hu<<HuO+cQPO<<HuO#UQQO'#DsO+hQPO7+$qOOQO7+$q7+$qO(^QQO,59`O)cQQO,59_O+pQPOAN>aOOQO,5:_,5:_OOQO-E7q-E7qOOQO<<H]<<H]O#UQQOG23{O+uQPOLD)gOOQW!$'MR!$'MRO#UQQO'#Du",
  stateData: ",P~O!nOSROS~OVRO~OUTO~OWUO~OPVO~O[WO![]O!^^O!c_O~OU`O~O^aO_aO`aOaaObaO~OQdO[WO![]O!^^O!c_O~OoeO~OofO~O!`gO~OUjO[WOkiOliOnlOolOplOqlOtkO~O!dvO~OWwO~OuxO~OUyO~OWzO~Ot{O~Ox!OOz!POWhXlhX|hX!WhX!YhXrhXuhX~O!PhX!QhX!RhX!ShX!ThX!UhX~P$cOl!TO|!SOWgX!WgX!YgXrgXugX~O!PgX!QgX!RgX!SgX!TgX!UgX~P%hO!P!WO!Q!WO!R!WO!S!WO!T!WO!U!WOWfX!WfX!YfXrfXufX~O!W!YOWeX!YeXreXueX~O!Y!]OWdXrdXudX~OW!`O~Or!bO~P#UOr!dO~Ox!OOz!POWhalha|ha!Wha!Yharhauha~O!Pha!Qha!Rha!Sha!Tha!Uha~P(^Ol!TO|!SOWga!Wga!Ygargauga~O!Pga!Qga!Rga!Sga!Tga!Uga~P)cO!W!YOWea!Yeareauea~O!Y!]OWdardauda~OW!pOu!qO~Or!tOu!rO~O!a!wO~Or!zOu!rO~O!`!{O~OW!}O~ORnUn~",
  goto: "'p!lPPPPP!mPPP!q!u!yP#]PPPPP#`#o#v$Q$]$i$y%_PP%mPPPPP!}PP!}%{P%{P&RP&R&ZPPPPPP&^P&bP!uP!uP&fPP!uPP&l&r&x'O'Y'd'jTPOQTZV[TYV[SXV[ilbkm{!Q!U!X!Z!^!r!{#ORbXQubQ|kQ!c{Q!x!rR!|!{Ztbk{!r!{Ysbk{!r!{R!n!^[rbk{!^!r!{R!l!Z^qbk{!Z!^!r!{R!k!X^pbk{!Z!^!r!{S!g!U#OR!j!X`obk{!U!Z!^!r!{Q}mQ!e!QT!i!X#Oimbkm{!Q!U!X!Z!^!r!{#Oinbkm{!Q!U!X!Z!^!r!{#OX!Qo!R!i!uS!Up!VT#O!j!vR!XqT!Zr![T!^s!_Qh_R!axQQORSQQ[VRc[Q!s!cR!y!sQ!RoS!f!R!uR!u!iQ!VpS!h!V!vR!v!jQ![rR!m![Q!_sR!o!_",
  nodeNames: "⚠ Indent Dedent Comment Program Node Identifier node Newline Statement Assignment Variable @ AssignmentOp = += -= *= /= Expression LogicalOr LogicalAnd Comparison Term Factor Unary UnaryOp ! - Primary Number String True False ) FunctionCall ( , ParenExpression MulOp * DivOp / AddOp + SubOp ComparisonOp == != >= <= > < LogicalAndOp && LogicalOrOp || Say say Choice choice Symbol : if Goto goto end",
  maxTerm: 76,
  nodeProps: [
    ["openedBy", 34,"("],
    ["closedBy", 36,")"]
  ],
  skippedNodes: [0,3],
  repeatNodeCount: 7,
  tokenData: ")f~RiXY!pYZ!{]^!{pq!pqr#Wrs#est%Rvw%jxy%uyz%zz{&P{|&^|}&k}!O&p!P!Q&}!Q!['[![!]'u!^!_'z!_!`(X!`!a(f!b!c(s!c!}(x#R#S(x#T#o(x#p#q)Z~!uQ!n~XY!ppq!p~#QQW~YZ!{]^!{U#]PkQ!_!`#`S#eO!QS~#hVOr#ers#}s#O#e#O#P$S#P;'S#e;'S;=`${<%lO#e~$SOo~~$VRO;'S#e;'S;=`$`;=`O#e~$cWOr#ers#}s#O#e#O#P$S#P;'S#e;'S;=`${;=`<%l#e<%lO#e~%OP;=`<%l#e~%WSR~OY%RZ;'S%R;'S;=`%d<%lO%R~%gP;=`<%l%R~%mPvw%p~%uO!W~~%zOt~~&POr~V&UPxU!_!`&XP&^OaPV&cP|U!_!`&fP&kO_P~&pOu~V&uPlU!_!`&xP&}O`PV'SPzU!_!`'VP'[ObP~'aQn~!O!P'g!Q!['[~'jP!Q!['m~'rPn~!Q!['m~'zO!`~~(PP!U~!_!`(S~(XO!S~T(^P^P!_!`(aS(fO!PS~(kP!T~!_!`(n~(sO!R~~(xO[~~(}SU~!Q![(x!c!}(x#R#S(x#T#o(x~)^P#p#q)a~)fO!Y~",
  tokenizers: [0, 1, 2, indentation],
  topRules: {"Program":[0,4]},
  specialized: [{term: 6, get: (value: keyof typeof spec_Identifier) => spec_Identifier[value] || -1}],
  tokenPrec: 502
})
